### ISSUE TITLE
Check why some columns are generated with "-1" and "-2" instead of 1's and 0's

### ISSUE THREAD

**Issue by gabe-nasc** [docardoso/logic-toolbox#9]
When generating the table for **(~a&b)|(a&b)** the function **truthtable** returned [this table](https://i.imgur.com/uIxr7VL.png)

**Comment by docardoso** [comment]
This happens because the boolean.py module uses "& | ~" as logic operators while truths module uses "and or not". Therefore, it is necessary to translate the expressions generated by the first to be parsed by the second.

Fortunately, there is a suggested solution: look for 'NOT2', 'AND2' and 'OR2' in the source code of boolean.py module .
